# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

server:
  port: 8098
  tomcat:
    use-relative-redirects: true

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/eproc
management:
  health:
    mongo:
      # Health check is disabled for the following reasons:
      # 1. The new Spring framework uses the 'hello' command for health checks, which is not supported by older versions of MongoDB.
      # 2. MongoDB is used only for process definitions outside the BPMN engine and does not affect Camunda's core functionality.
      # 3. MongoDB will be removed in future releases.
      enabled: false
# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
#
# More documentation is available at:
# https://www.jhipster.tech/common-application-properties/
# ===================================================================

# application:

ecos-app:
  id: ecos-process
  version: 1.0.0
  name: ECOS Process

ecos-process:
  bpmn:
    first-enabled-proc-def:
      cache:
        hazelcast:
          timeToLiveSeconds: 3
          maxSizeConfig:
            size: 300
          evictionPolicy: LRU
    async-start-process:
      consumer:
        count: 4
        prefetch: 250
        retry:
          max-attempts: 1200
    kpi:
      mutation-processor:
        consumer:
          count: 2
          prefetch: 250
          retry:
            max-attempts: 1200
    elements:
      listener:
        enabled: true
      mutation-processor:
        consumer:
          count: 8
          prefetch: 250
          retry:
            max-attempts: 1200
  timers:
    delay-after-fail-ms: 600000
    update-rate-ms: 30000
  tasks:
    dto-converter:
      cache:
        hazelcast:
          timeToLiveSeconds: 300
          maxSizeConfig:
            size: 3000
          evictionPolicy: LRU
    historic-dto-converter:
      cache:
        hazelcast:
          timeToLiveSeconds: 3600
          maxSizeConfig:
            size: 5000
          evictionPolicy: LRU

ecos:
  webapp:
    task:
      executors:
        bpmn-rabbitmq:
          corePoolSize: 32
    dataSources:
      camunda:
        url: jdbc:postgresql://localhost:14523/ecos_camunda
        username: camunda
        password: camundapassword
        xa: true
      eproc:
        url: jdbc:postgresql://localhost:14523/ecos_process
        username: process
        password: processpassword
        xa: true
      bpmn-rabbitmq:
        executor: bpmn-rabbitmq
        name: BPMN rabbitmq connection
        type: rabbitmq
        host: ${ecos.webapp.dataSources.main-rabbitmq.host}
        username: ${ecos.webapp.dataSources.main-rabbitmq.username}
        password: ${ecos.webapp.dataSources.main-rabbitmq.password}
    x509:
      keys:
        application:
          location: classpath:ecos/x509/keys/application.key

camunda:
  bpm:
    admin-user:
      id: admin
      password: admincamundapassword
    authorization:
      enabled: false
    webapp:
      application-path: /camunda
    database:
      # schema is managed by liquibase. See src/main/resources/ecos/liquibase/camunda/master.xml
      schemaUpdate: 'false'
