# Старт инстанса процесса

# @name ProcessInstanceStart
POST http://localhost/gateway/api/records/mutate
Authorization: Basic admin admin
Content-Type: application/json

{
  "records": [
    {
      "id": "eproc/bpmn-proc@process_different_1",
      "attributes": {
        "action": "START",
        "document": "emodel/alrosa-contract@0b54aed0-d288-4d29-aec3-c1ff37cfa089"
      }
    }
  ]
}

