# Создание переменной процесса (объекта)
#
# name - имя переменной
# executionId - id execution (id процесса)
# type - тип переменной, при создании объекта - object
# objectTypeName - имя класса объекта
# value - значение переменной в формате json
#

# @name ProcessVariableCreateObject
POST http://localhost/gateway/api/records/mutate
Authorization: Basic admin admin
Content-Type: application/json

{
    "records": [
        {
            "id": "eproc/bpmn-variable-instance@",
            "attributes": {
                "name": "newTestVariable",
                "executionId": "bb4d473c-675c-11ee-96b1-fa02e06f9ec1",
                "type": "object",
                "objectTypeName": "java.util.ArrayList<ru.citeck.ecos.process.domain.bpmn.model.ecos.task.user.TaskOutcome>",
                "value": "[{\"id\":\"send_for_approval\",\"name\":{\"ru\":\"Отправить на согласование\"},\"config\":{\"theme\":\"PRIMARY\"}}]"
            }
        }
    ]
}

