# Скрин просмотра определенной версии процесса. Список запущенных процессов.

# В списке пользователю показываем:
#
# Статус - какая-то иконка, Ок / Не ок. В зависимости от наличия инцидентов.
# Если isSuspended = true, то рисуем иконку "пауза"
#
# id (ID) - ссылка, по нажатию провалдиваемся в просмотр инстанса в рамках админки.
# Пользователю отображаем id инстанса, например 5bde4da9-5d26-11ee-a087-22e5aeaa8a65
#
# document (Документ) - Документ, по которому запущен БП (ссылка)
#
# startTime (Время старта)
#
# Поддерживается сортировка только по startTime, она зашита по умолчанию.
# В список добавить возможность сортировки по startTIme asc / desc
#
# В query параметр bpmnDefEngine обязательный
# Добавить возможность фильтрации по `document` - entityRef. Пример см ProcessDefinitionViewProcessInstancesFilterDocument

# @name ProcessDefinitionViewProcessInstances
POST http://localhost/gateway/api/records/query
Authorization: Basic admin admin
Content-Type: application/json

{
    "query": {
        "sourceId": "eproc/bpmn-proc",
        "query": {
            "att": "bpmnDefEngine",
            "t": "eq",
            "val": "eproc/bpmn-def-engine@a1795c90-5dd0-11ee-9787-62d3dfa44630"
        },
        "page": {
            "maxItems": 30,
            "skipCount": 0
        },
        "sortBy": [
            {
                "ascending": false,
                "attribute": "startTime"
            }
        ]
    },
    "attributes": {
        "disp": "?disp",
        "isSuspended": "isSuspended?bool",
        "document": "documentRef",
        "startTime": "startTime",
        "incidents": "incidents[]{?id}"
    }
}

