# Скрин просмотра определенного инстанса процесса. Список переменных.

# В списке пользователю показываем:
#
# name (Имя) - имя переменной
# type (Тип) - тип переменной
#
# value (Значение) - строкове представление переменной.
# С значением покащываем всплывающую кнопку для копирования значения в буфер обмена.
# Если переменная имеет тип "json", "xml", "object" то значениеь должно быть ссылкой. По клику на ссылку открывается
# модальное окно с просмотром содержимого переменной и возможность отредактировать (richtext, желательно с code style).
# При сохранении отправляем запрос: TODO
# |
# Если тип "object" то форма редактирования должна содержать поля:
# typedValueInfo.objectTypeName (Тип объекта)
# typedValueInfo.serializationDataFormat (Формат сериализации)
# typedValueInfo.errorMsg (Ошибка десериализации) - Если поле пришло пустое, то не показываем его.
# |
# На форме должно быть две вкладки: "Сериализованное значение" и "Десериализованное значение", соответственно показываем
# значения:
# serializableValue.serialized (Сериализованное значение)
# serializableValue.deserialized (Десериализованное значение)
#
#
# activityInstanceId (Область видимости) - Кликабельная ссылка, с отображением:
# Может прийти стркоа в двух форматах:
# "bb4d473c-675c-11ee-96b1-fa02e06f9ec1" - это id инстанса процесса
# или с разделителем ":" - "Activity_0gj8byg:bc5e1b19-675c-11ee-96b1-fa02e06f9ec1" - это id activity в процессе
# Для пользователя мы должны показать читаемое значение, а не сам id:
# Для id процесса получаем через `eproc/bpmn-proc@{id}`, атрибут ?disp
# Для id activity необходимо взять то, что идет до разделителя ":" и получить имя элемента (mltext) из схемы процесса
#
# По клику добавляем в фильтр сортировки текущего списка переменных поле activityInstanceId. Смысл в том, что если
# пользователь кликнул на ссылку, то он хочет увидеть все переменные, которые есть в рамках этой области видимости.
# Должна быть возможность сбросить фильтр.
#
# Пагинация поддерживается.
# Сортировка по умолчанию идет по имени переменной.
# В список добавить возможность сортировки name - asc / desc
#
# Добавить окно поиска с фильтрацией по `name`, `activityInstanceId`. Пример см ProcessInstanceViewProcessVariablesFilter

# @name ProcessInstanceViewProcessVariables
POST http://localhost/gateway/api/records/query
Authorization: Basic admin admin
Content-Type: application/json

{
    "query": {
        "sourceId": "eproc/bpmn-variable-instance",
        "query": {
            "att": "processInstance",
            "t": "eq",
            "val": "eproc/bpmn-proc@bb4d473c-675c-11ee-96b1-fa02e06f9ec1"
        },
        "page": {
            "maxItems": 30,
            "skipCount": 0
        }
    },
    "attributes": {
        "name": "name",
        "type": "type",
        "value": "value",
        "typedValueInfo": "typedValueInfo?json",
        "serializableValue": "serializableValue?json",
        "activityInstanceId": "activityInstanceId"
    }
}

