---
id: bpmn-kpi-settings
name:
  en: Bpmn KPI Settings
  ru: Настройка BPMN KPI
system: true
storageType: ECOS_MODEL
formRef: uiserv/form@bpmn-kpi-settings-form
journalRef: uiserv/journal@bpmn-kpi-settings
dispNameTemplate:
  ru: '${name}'
actions:
  - uiserv/action@download-text-yml
  - uiserv/action@edit
  - uiserv/action@edit-json
  - uiserv/action@delete
defaultCreateVariant: true
createVariants:
  - id: upload
    name:
      ru: Загрузить конфигурацию
      en: Upload configuration
    formRef: uiserv/form@ecos-artifact-upload
model:
  attributes:
    - id: name
      name:
        ru: Название
        en: Name
    - id: kpiType
      name:
        ru: Тип
        en: Type
    - id: enabled
      name:
        ru: Включен
        en: Enabled
      type: BOOLEAN
    - id: processRef
      name:
        ru: Процесс
        en: Process
      type: ASSOC
      config:
        typeRef: emodel/type@bpmn-proc-latest
    - id: dmnCondition
      name:
        ru: Условие
        en: Condition
      type: ASSOC
    - id: sourceBpmnActivityId
      name:
        ru: Исходный BPMN элемент
        en: Source BPMN Activity
    - id: sourceBpmnActivityEvent
      name:
        ru: Событие исходного BPMN элемента
        en: Source BPMN Activity Event
    - id: targetBpmnActivityId
      name:
        ru: Целевой BPMN элемент
        en: Target BPMN Activity
    - id: targetBpmnActivityEvent
      name:
        ru: Событие целевого BPMN элемента
        en: Target BPMN Activity Event
    - id: durationKpi
      name:
        ru: KPI по длительности
        en: Duration KPI
    - id: durationKpiTimeType
      name:
        ru: Тип времени
        en: Duration type
    - id: countKpi
      name:
        ru: KPI по количеству
        en: Count KPI
      type: NUMBER
    - id: countPeriod
      name:
        ru: Период
        en: Period
    - id: kpiAsNumber
      name:
        ru: KPI
        en: KPI
      type: NUMBER
      computed:
        type: SCRIPT
        config:
          fn: |-
            // Function to convert human-readable duration to milliseconds
            function parseDurationToMillis(duration) {
                // Regular expression to match units and values
                var regex = /(\d+)([dhms])/g;

                // Mapping of unit characters to milliseconds
                var unitMap = {
                    'd': 24 * 60 * 60 * 1000, // days to milliseconds
                    'h': 60 * 60 * 1000,      // hours to milliseconds
                    'm': 60 * 1000,           // minutes to milliseconds
                    's': 1000                 // seconds to milliseconds
                };

                var totalMilliseconds = 0;
                var match;

                while ((match = regex.exec(duration)) !== null) {
                    var value = parseInt(match[1]);
                    var unit = unitMap[match[2]];

                    totalMilliseconds += value * unit;
                }

                return totalMilliseconds;
            }

            var durationKpi = value.load("durationKpi");
            var countKpi = value.load("countKpi?num");

            if (durationKpi !== null && durationKpi.trim().length !== 0) {
                return parseDurationToMillis(durationKpi);
            }

            if (countKpi !== null) {
                return countKpi;
            }

            throw new Error("Не задана норма kpi");
        storingType: ON_MUTATE
