//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.02.05 at 07:02:39 AM GMT+07:00
//

@jakarta.xml.bind.annotation.XmlSchema(
    namespace = "http://www.omg.org/spec/BPMN/20100524/MODEL",
    elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED,
    xmlns = {
        @jakarta.xml.bind.annotation.XmlNs(prefix = "xsd", namespaceURI = "http://www.w3.org/2001/XMLSchema"),
        @jakarta.xml.bind.annotation.XmlNs(prefix = "dc", namespaceURI = "http://www.omg.org/spec/DD/20100524/DC"),
        @jakarta.xml.bind.annotation.XmlNs(prefix = "di", namespaceURI = "http://www.omg.org/spec/DD/20100524/DI"),
        @jakarta.xml.bind.annotation.XmlNs(prefix = "bpmndi", namespaceURI = "http://www.omg.org/spec/BPMN/20100524/DI"),
        @jakarta.xml.bind.annotation.XmlNs(prefix = "bpmn", namespaceURI = "http://www.omg.org/spec/BPMN/20100524/MODEL"),
        @jakarta.xml.bind.annotation.XmlNs(prefix = "xsi", namespaceURI = "http://www.w3.org/2001/XMLSchema-instance"),
        @jakarta.xml.bind.annotation.XmlNs(prefix = "ecos", namespaceURI = "http://www.citeck.ru/ecos/bpmn/1.0"),
        @jakarta.xml.bind.annotation.XmlNs(prefix = "camunda", namespaceURI = "http://camunda.org/schema/1.0/bpmn")
    }
)
package ru.citeck.ecos.process.domain.bpmn.model.omg;
