//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.05 at 07:02:39 AM GMT+07:00 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.omg.org/spec/BPMN/20100524/MODEL", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.citeck.ecos.process.domain.bpmn.model.omg;
