package ru.citeck.ecos.process.domain.bpmn.engine.camunda.services.beans

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test
import org.mockito.kotlin.any
import org.mockito.kotlin.mock
import org.mockito.kotlin.verify
import org.mockito.kotlin.whenever
import ru.citeck.ecos.bpmn.commons.values.Time
import ru.citeck.ecos.wkgsch.lib.calendar.WorkingCalendarImpl
import ru.citeck.ecos.wkgsch.lib.schedule.WorkingScheduleService
import ru.citeck.ecos.wkgsch.lib.schedule.dto.WorkingDayTime
import ru.citeck.ecos.wkgsch.lib.schedule.type.weekly.WeeklyWorkingSchedule
import ru.citeck.ecos.wkgsch.lib.schedule.type.weekly.WeeklyWorkingScheduleConfig
import java.time.DayOfWeek
import java.time.Instant
import java.time.LocalDate
import java.time.ZoneOffset

/**
 * Day-based methods of the `Time` script bean, pinned against a NON-UTC schedule.
 *
 * `plusWorkingDays` / `nowPlusWorkingDays` used to carry `@Deprecated("Not stable")` because
 * `schedule.addWorkingDays` classified an `Instant` by its UTC calendar day while the schedule's own
 * working hours live in `workingDayTimeZone`. For a `+03:00` schedule that is an off-by-one for every
 * instant in the 21:00..24:00 UTC window: UTC still sees the previous day while the schedule already
 * sees the next one. Fixed in ecos-working-schedule 1.5.0 (`a085dfb`), the version this project
 * resolves through the webapp parent.
 *
 * The day-boundary cases below are what makes the deprecation removal evidence-backed rather than a
 * guess about a library bump: they fail on 1.4.5 and pass on 1.5.0.
 */
class CamundaProcessTimeCalcTest {

    companion object {
        private val SCHEDULE_ZONE: ZoneOffset = ZoneOffset.of("+3")
        private const val CUSTOM_SCHEDULE_ID = "custom-schedule"
    }

    private val schedule = WeeklyWorkingSchedule(
        WorkingCalendarImpl(
            emptyMap(),
            LocalDate.EPOCH,
            LocalDate.parse("3000-01-01")
        ),
        WeeklyWorkingScheduleConfig(
            workingDayStart = WorkingDayTime.valueOf("09:00"),
            workingDayEnd = WorkingDayTime.valueOf("17:00"),
            workingDayTimeZone = SCHEDULE_ZONE
        )
    )

    private val workingScheduleService: WorkingScheduleService = mock()

    private val timeNowProvider: TimeNowProvider = mock()

    private val timeCalc = CamundaProcessTimeCalc(workingScheduleService, timeNowProvider)

    init {
        whenever(workingScheduleService.getScheduleById(any())).thenReturn(schedule)
    }

    /**
     * Friday 01:30 in the schedule zone, still Thursday in UTC. One working day later is Monday —
     * classifying the start day in UTC would answer Friday, which in the schedule zone is Saturday.
     */
    @Test
    fun `plus working days at the day boundary counts days in the schedule zone`() {
        val friday0130InScheduleZone = Instant.parse("2026-06-18T22:30:00Z")

        val result = timeCalc.plusWorkingDays(Time.of(friday0130InScheduleZone), 1)

        assertThat(result.instant).isEqualTo(Instant.parse("2026-06-21T22:30:00Z"))
        assertThat(result.instant.atZone(SCHEDULE_ZONE).toLocalDate())
            .isEqualTo(LocalDate.of(2026, 6, 22))
        assertThat(result.instant.atZone(SCHEDULE_ZONE).dayOfWeek).isEqualTo(DayOfWeek.MONDAY)
    }

    /**
     * The same boundary through the `now`-based entry point — this is the one production actually
     * reaches, via the expression generated by `TaskDueDateManualExpressionConverter`.
     */
    @Test
    fun `now plus working days at the day boundary counts days in the schedule zone`() {
        val friday0130InScheduleZone = Instant.parse("2026-06-18T22:30:00Z")
        whenever(timeNowProvider.now()).thenReturn(Time.of(friday0130InScheduleZone))

        val result = timeCalc.nowPlusWorkingDays(1)

        assertThat(result.instant).isEqualTo(Instant.parse("2026-06-21T22:30:00Z"))
        assertThat(result.instant.atZone(SCHEDULE_ZONE).dayOfWeek).isEqualTo(DayOfWeek.MONDAY)
    }

    /**
     * Monday 01:30 in the schedule zone, still Sunday in UTC. Backwards over the same boundary.
     */
    @Test
    fun `minus working days at the day boundary counts days in the schedule zone`() {
        val monday0130InScheduleZone = Instant.parse("2026-06-21T22:30:00Z")

        val result = timeCalc.plusWorkingDays(Time.of(monday0130InScheduleZone), -1)

        assertThat(result.instant).isEqualTo(Instant.parse("2026-06-18T22:30:00Z"))
        assertThat(result.instant.atZone(SCHEDULE_ZONE).dayOfWeek).isEqualTo(DayOfWeek.FRIDAY)
    }

    /**
     * Plain in-working-hours arithmetic: the weekend is skipped and the clock time is preserved.
     */
    @Test
    fun `plus working days skips the weekend and keeps the time of day`() {
        val fridayMorning = Instant.parse("2026-06-19T08:00:00Z")

        val result = timeCalc.plusWorkingDays(Time.of(fridayMorning), 1)

        assertThat(result.instant).isEqualTo(Instant.parse("2026-06-22T08:00:00Z"))
    }

    @Test
    fun `plus working days without schedule id uses the default schedule`() {
        timeCalc.plusWorkingDays(Time.of(Instant.parse("2026-06-19T08:00:00Z")), 1)

        verify(workingScheduleService).getScheduleById("DEFAULT")
    }

    @Test
    fun `now plus working days passes the requested schedule id through`() {
        whenever(timeNowProvider.now()).thenReturn(Time.of(Instant.parse("2026-06-19T08:00:00Z")))

        timeCalc.nowPlusWorkingDays(1, CUSTOM_SCHEDULE_ID)

        verify(workingScheduleService).getScheduleById(CUSTOM_SCHEDULE_ID)
    }
}
