id: dmn-section-root-settings

recordRef: eproc/dmn-section@ROOT
inherit: false

settings:

  - authorities:
      - GROUP_bp-administrator
    permissions:
      - emodel/permission-def@read
      - emodel/permission-def@write
      - emodel/permission-def@dmn-def-deploy
      - emodel/permission-def@dmn-instance-edit
      - emodel/permission-def@dmn-section-create-dmn-def
      - emodel/permission-def@dmn-section-edit-dmn-def

  - authorities:
      - GROUP_bp-developer
    permissions:
      - emodel/permission-def@read
      - emodel/permission-def@bpmn-process-def-deploy
